apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webservice-vs
spec:
  hosts:
    - webservice
  http:
#  - fault:
#      abort:
#        httpStatus: 503
#        percentage:
#          value: 100
#      delay:
#        fixedDelay: 5s
#        percentage:
#          value: 50
    - route:
        - destination:
            host: webservice
            subset: v0
          weight: 50
        - destination:
            host: webservice
            subset: v1
          weight: 50
