management:
  endpoint:
    shutdown:
      enabled: true # endpoint 활성화, 특정 엔드포인트를 활성화 하려면 `management.endpoint.{엔드포인트명}.enabled=true` 를 적용하면 된다.
    health:
      show-components: always # 헬스 정보를 자세히
  #      show-details: always # 헬스 정보를 간략하게
  endpoints:
    web:
      exposure:
        include: "*" # endpoint 웹 노출
  metrics:
    distribution:
#      percentiles-histogram:
#        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99

logging:
  level:
    org.example.bootmonitoring.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true